### ISSUE TITLE
HPC Pack error

### ISSUE THREAD

**Issue by alemcuevas** [MsHpcPack/HPCPack2016#4]
Hi @MsHpcPack @amat27 , 
I was trying to deploy the second options of your templates, but the portal gives me this error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidParameter\",\r\n \"target\": \"imageReference.version\",\r\n \"message\": \"The value of parameter imageReference.version is invalid.\"\r\n }\r\n}"}]}

My image reference version is set to 'latest'

Any ideas of what I could do?
Thanks in advance!

**Comment by UCdavidUC** [comment]
I just had the same Issue when deploying the template and creating the SQL Server image, in the reference says we should use 'latest' but when running the script, it just breaks and displays the error message: "The value of parameter imageReference.version is invalid."

Regards!

**Comment by alemcuevas** [comment]
I found the problem: The 'MicrosoftSQLServer:SQL2016-WS2012R2:Standard:latest' is not available; you can check which version of that image is avaible and suits you in this link. 
https://github.com/gatneil/armtg/blob/master/vm_image_list.html 

That would be the answer.

Regards!
