### ISSUE TITLE
Fail to install HPC pack 2016 U1 on Head Node

### ISSUE THREAD

**Issue by hirtanak** [MsHpcPack/HPCPack2016#8]
I faced the deployment issue in "Template 1: High-availability cluster for Windows workloads with new Active Directory Domain" Any suggestion?

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'setupHpcHeadNode'. Error message: \\\"DSC Configuration 'InstallHpcNode' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_xHpcNodeInstall failed to execute Set-TargetResource functionality with error message: Failed to Install HPC HeadNodePreReq (errCode=13818): the certificate doesn't meet the requirements. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by MsHpcPack** [comment]
The error means the certificate you are using is not qualified. Please use a qualified certificate described in Pre-Requisites.
